### PR TITLE
[WIP] Parallel implementation of numba code

### PR DESCRIPTION
**Pull request by darribas**
This PR adds a parallel implementation to the `numba` option in `Moran_Local`. Still work in progress and parallelisation needs to be added. It already has a restructuring of 831e6ac that produces the same results on a single core but is ready to be fitted with a `Parallel` implementation with `joblib`.

### CODE REVIEW

**Comment by ljwolf** [comment]
Hey, thanks for this! I thought we agreed this strategy [here](https://github.com/pysal/esda/pull/116#issuecomment-622966970) with @sjsrey taking a first stab in #4? Broadly speaking, this means w/ @sjsrey's commit, we do something like:
```python
from joblib import delayed, Parallel
Parallel(n_jobs=n_jobs)(
    delayed(_do_one_observation)(
        (i, z, permuted_ids, weights, start, cardinalities, mask, observed, scaling) 
        for i in range(n))
)
```
This can also be done for permutations:
```python
def random_seed_permutation(n, k, seed):
    numpy.random.seed(seed)
    return numpy.random.choice(n, k, replace=False)

Parallel(n_jobs=n_jobs)(
    delayed(random_seed_permutation)(
        (n-1, max_card, seed) 
        for seed in numpy.random.randint(10000, size=n_permutations))
)
```

This is the same general pattern use elsewhere (e.g. scikit [1](https://github.com/scikit-learn/scikit-learn/blob/60b8fb221b5ebb17a0454b36e1f1b4fc3e4c4ba7/sklearn/cluster/_mean_shift.py#L394),[2](https://github.com/scikit-learn/scikit-learn/blob/02309ffbdaae45af75b0e87946aab9aedb6b3634/sklearn/manifold/_mds.py#L259), or [`joblib`'s own recommendation](https://joblib.readthedocs.io/en/latest/parallel.html))... I think it's generally faster, but I don't know. 

I think we did not see significant speedups using numba's own `prange`, which ships each iteration to a different thread (I think), because we were getting odd answers with `njit(parallel=True)`. without `parallel=True`, `prange` is just `range`. 

Anyway, I'd like to compare the performance of chunking vs. the strategy recommended by joblib used in sklearn... chunking may be faster because the starting indices (computed using `numpy.cumsum()` in #4) are on the n-length array of cardinalities.

**Comment by darribas** [comment]
Yes, it's a different approach, which I wanted to try out, hence why it's a separate PR. I want to finish a working version to see to what extent it works and how well it does. Then we can see which one we keep?

If I read it correctly, the approach in #4 ships full objects (all of z, cardinalities, etc.) to each worker which might be more memory demanding?

I've read a bit more about `prange` and want to try a couple of options before we fully discard it. More (hopefully) soon...

**Comment by ljwolf** [comment]
definitely! Just documenting these are conceptually distinct 😄 we'll do well to pick the best from a big bunch. Now, we've got:
1. joblib embarassingly parallel, possibly using memory mapping on the shared inputs
2. chunking here
3. prange

**Comment by ljwolf** [comment]
I get a change from 3.45s to 2.6s w/ 8 jobs on a machine:
```
➜  ~ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    2
Core(s) per socket:    4
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 158
Model name:            Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
Stepping:              9
CPU MHz:               3805.734
CPU max MHz:           4200.0000
CPU min MHz:           800.0000
BogoMIPS:              7200.64
Virtualisation:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              8192K
NUMA node0 CPU(s):     0-7
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb invpcid_single intel_pt ssbd ibrs ibpb stibp kaiser tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt xsaveopt xsavec xgetbv1 dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d
```
I have some massive GWR simulations *still* running (1 month and counting) so let me shut those off and try again.

**Comment by darribas** [comment]
An update on this PR:

- As of e0bfc76, a parallel implementation relying on numba's `prange` is complete and returns correct p-values, albeit more slowly than the "single-thread" alternative. For the time being thus, this route is discarded
- As of efbbe99, there is a joblib-based implementation that limits the number of inner threads and chunks the jobs in an efficient way and this does seem to speed things up. The only remaining bits that could be looked for in terms of further optimizations (that I can think of) relate to dispatching of the chunks ([`L.1728`](https://github.com/ljwolf/esda/blob/efbbe99c6e37695394a40a9e0433a715bbef268b/esda/moran.py#L1728)), in that it might be possible to use a generator to avoid apending chunks to a list.

**Comment by ljwolf** [comment]
Super! There are some merge conflicts with @sjsrey's work, so I'll resolve & rebase. I still see very stable performance locally, and I'm real glad the `inner_max_num_threads` suggestion worked so well. 

I've explored extending this in the way we discussed, like a numba-compiled generator for the chunks or memory-mapping `z` to avoid copy over the jobs. 

I get the same timings locally with `njobs=2` jobs on my MBP. I need to check further, but I'll be checking on my lab computer for stable timings tonight:

| Version  | Data | Platform | Speed |
| ---------|---- | -------|------ |
| Master | NAT |  MBP i5 | 3.32 +/- 264 ms (7 reps) |
| Numba chunks | NAT | MBP i5| 546 ms +/- 22.4 ms (7 reps)|
| Numba chunks + generator | NAT | MBP i5| 407 +/- 15.5 ms (7 reps) |
| Numba chunks + memmapping `z`| NAT | MBP i5| 418 ms +/- 6.95 ms (7 reps) | 
| Numba chunks + memmapping `z` + generator | NAT |  MBP i5| 404 +/- 54.2 ms (7 reps) |
| Master | NAT | i7-7700 | 2.01s +/- 32.93 ms (1000 reps) |
| Numba chunks  |  NAT | i7-7700 | 379.77 ms +/- 10.10 ms (1000 reps) | 
| Numba chunks + generator | NAT | i7-7700| 384.80 ms +/- 21.61 ms (1000 reps) |
| Numba chunks + memmapping `z` |  NAT | i7-7700 | 382.07 ms +/- 9.53 ms (1000 reps) | 
| Numba chunks + memmapping `z` + generator | NAT | i7-7700| 381 ms +/- 11.45 ms (1000 reps) |

**Comment by ljwolf** [comment]
While it looks like using the memmap & generator together gives a decent further speedup in some runs, it's not critical. The generator & memmap should result in lower memory pressure, generally speaking, because it does not copy `z` for every chunk. 

It should be transparent when the data can be held in ram. Using `tempfile.SpooledTemporaryFile()`, we can build a "file" that lives in RAM for the memory map, and only write it to disk if `z` is larger than ram.

**Comment by ljwolf** [comment]
This has been rebased & merged, along with first steps towards making the deployment more generic, so that all local statistics can use the functionality.

**Pull request merged**
